---
title: "simulation_data"
author: "Thu Pham"
date: "2023-01-31"
output: pdf_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
root <- "/n/home04/thupham17/thesis/"
# root <- "/Users/thupham/Desktop/thesis/"
```

```{r}
load.all.sims = function( filehead ) {
  
  files = list.files( filehead, full.names=TRUE)
  
  res = map_df( files, function( fname ) {
    # cat( "Reading results from ", fname, "\n" )
    rs = readRDS( file = fname )
    rs$filename = fname
    rs$result
  })
  res
}
```

```{r}
# scale <- load.all.sims(paste0(root, "results/icc_scale/"))
# write.csv(scale, paste0(root, "concat_results/icc_scale.csv"))
# sigma_r <- load.all.sims(paste0(root, "results/icc_sigma_r"))
# write.csv(sigma_r, paste0(root, "concat_results/icc_sigma_r.csv"))
# snr <- load.all.sims(paste0(root, "results/icc_new_outcome"))
# write.csv(snr, paste0(root, "concat_results/icc_snr.csv"))
snr_cluster_2 <- load.all.sims(paste0(root, "results/icc_spurious_2"))
write.csv(snr_cluster_2, paste0(root, "concat_results/icc_cluster_2.csv"))
```


```{r}
scale <- read.csv(paste0(root, "concat_results/icc_scale.csv"))
sigma_r <- read.csv(paste0(root, "concat_results/icc_sigma_r.csv"))
snr <- read.csv(paste0(root, "concat_results/icc_snr.csv"))
snr_cluster <- read.csv(paste0("/Users/thupham/Desktop/thesis/concat_results", 
                                "/icc_spurious.csv"))
```

```{r}
# no NA values, so assume that each went through full 1000 reps!
scale_low_snr <- scale %>%
  filter(snr < 1) %>%
  group_by(scale) %>%
  summarize(across(mean_adj_r_squared:last_col(), ~ mean(.x, na.rm = TRUE)),
            across(reps, sum)) %>%
  ungroup()

scale_high_snr <- scale %>%
  filter(snr > 1) %>%
  group_by(scale) %>%
  summarize(across(mean_adj_r_squared:last_col(), ~ mean(.x, na.rm = TRUE)),
            across(reps, sum)) %>%
  ungroup()

sigma_r_low_snr <- sigma_r %>%
  filter(snr < 1) %>%
  group_by(sigma_r) %>%
  summarize(across(mean_adj_r_squared:last_col(), ~ mean(.x, na.rm = TRUE)),
            across(reps, sum)) %>%
  ungroup()

sigma_r_high_snr <- sigma_r %>%
  filter(snr > 1) %>%
  group_by(sigma_r) %>%
  summarize(across(mean_adj_r_squared:last_col(), ~ mean(.x, na.rm = TRUE)),
            across(reps, sum)) %>%
  ungroup()

sigma_r_snr <- rbind(sigma_r_high_snr, sigma_r_low_snr) %>%
  mutate(snr_level = factor(rep(c("high", "low"), 
                                each = nrow(sigma_r_high_snr)))) %>%
  mutate(sigma_r = sigma_r^2) %>%
  mutate(min_agreement = mean_agreement - sd_agreement,
         max_agreement = mean_agreement + sd_agreement)

scale_snr <- rbind(scale_high_snr, scale_low_snr) %>%
  mutate(snr_level = factor(rep(c("high", "low"), 
                                each = nrow(scale_high_snr)))) %>%
  mutate(min_agreement = mean_agreement - sd_agreement,
         max_agreement = mean_agreement + sd_agreement)

snr_collapse_cluster <- snr_cluster %>%
  group_by(snr) %>%
  summarize(across(mean_adj_r_squared:last_col(), ~ mean(.x, na.rm = TRUE)),
          across(reps, sum)) %>%
  ungroup()

snr_collapse_cluster <- snr_collapse_cluster %>%
  mutate(min_agreement = mean_agreement - sd_agreement,
         max_agreement = mean_agreement + sd_agreement)

snr_collapse <- snr %>%
  group_by(snr) %>%
  summarize(across(mean_adj_r_squared:last_col(), ~ mean(.x, na.rm = TRUE)),
          across(reps, sum)) %>%
  ungroup()

snr_collapse <- snr_collapse %>%
  mutate(min_agreement = mean_agreement - sd_agreement,
         max_agreement = mean_agreement + sd_agreement) %>%
  filter(snr %in% snr_collapse_cluster$snr)
  
```

```{r}
sigma_r_snr_plot <- ggplot(sigma_r_snr, mapping = aes(x = sigma_r,
                        y = mean_agreement,
                        ymin = min_agreement,
                        ymax = max_agreement,
                        group = snr_level,
                        color = snr_level)) +
  geom_line() + 
  geom_point() +
  geom_ribbon(alpha = 0.25) + 
  ggtitle("Mean Agreement vs. Variance of Clusters") +
  ylab("Mean Agreement") + 
  xlab("Variance of Clusters") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(name = "SNR Level",
                     labels=c('High', 'Low'),
                      values = c("#56B4E9", "#CC79A7"))

sigma_r_snr_plot
ggsave(paste0("/Users/thupham/Desktop/thesis/plots/final_plots/",
       "agreement_snr_sigma_r.png"))

scale_snr_plot <- ggplot(scale_snr, mapping = aes(x = scale,
                        y = mean_agreement,
                        ymin = min_agreement,
                        ymax = max_agreement,
                        group = snr_level,
                        color = snr_level)) +
  geom_line() + 
  geom_point() +
  geom_ribbon(alpha = 0.25) + 
  ggtitle("Mean Agreement vs. Scale") +
  ylab("Mean Agreement") + 
  xlab("Scale") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(name = "SNR Level",
                     labels=c('High', 'Low'),
                      values = c("#56B4E9", "#CC79A7"))

scale_snr_plot
ggsave(paste0("/Users/thupham/Desktop/thesis/plots/final_plots/",
       "agreement_snr_scale.png"))
```

```{r}
agreement <- data.frame(snr = c(0.42, 0.23, 1.28),
                        mean_agreement = c(0.427027, 0.1984733, 0.00591716),
                        min_agreement = c(0.427027, 0.1984733, 0.00591716),
                        max_agreement = c(0.427027, 0.1984733, 0.00591716),
                        outcome = factor(c("MEFS", "LTR", "Hybrid")))
```



```{r}
snr_plot <- ggplot(snr_collapse, mapping = aes(x = snr,
                        y = mean_agreement,
                        ymin = min_agreement,
                        ymax = max_agreement)) +
  geom_line(color = "#CC79A7") + 
  geom_ribbon(alpha = 0.25) + 
  geom_point(color = "#CC79A7") +
  ggtitle("Mean Agreement vs. SNR") +
  ylab("Mean Agreement") + 
  xlab("Signal to Noise Ratio") + 
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = 'bottom') +
  geom_point(data = agreement, 
             mapping = aes(color = outcome)) +
  guides(color=guide_legend(title="ELS@H Data"))

snr_plot
ggsave(paste0("/Users/thupham/Desktop/thesis/plots/final_plots/",
       "agreement_snr.png"))
```

```{r}
snr_plot_2 <- ggplot(snr_collapse_cluster, mapping = aes(x = snr,
                        y = mean_agreement,
                        ymin = min_agreement,
                        ymax = max_agreement)) +
  geom_line(color = "#CC79A7") + 
  geom_ribbon(alpha = 0.25) + 
  geom_point(color = "#CC79A7") +
  ggtitle("Mean Agreement vs. SNR") +
  ylab("Mean Agreement") + 
  xlab("Signal to Noise Ratio") + 
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = 'bottom') 
# +
#   geom_point(data = agreement, 
#              mapping = aes(color = outcome)) +
#   guides(color=guide_legend(title="ELS@H Data"))

snr_plot_2
ggsave(paste0("/Users/thupham/Desktop/thesis/plots/final_plots/",
       "agreement_snr_cluster.png"))
```


```{r}
variable_names <- list(
  "high" = "Higher SNR (1.28)" ,
  "low" = "Lower SNR (0.30)"
)


variable_labeller <- function(variable, value){
  return(variable_names[value])
}
```


```{r}
# fm_metrics <- colnames(sigma_r_snr %>% dplyr::select(ends_with("ixed")))
longer_y_rmse_sigma_r <- pivot_longer(sigma_r_snr, 
                       cols = c("mean_y_rmse_fixed",
                                "mean_y_rmse_mixed"),
                       names_to = "effects",
                       values_to = "y_rmse") %>%
  mutate(effects = substrRight(effects, 5)) %>%
  dplyr::select(c("y_rmse", "effects", "snr_level", "sigma_r",
           "mean_adj_r_squared", "mean_icc"))

p <- ggplot(data = longer_y_rmse_sigma_r, 
       mapping = aes(x = sigma_r^2, y = y_rmse,
                     group = factor(effects),
                     color = factor(effects))) + 
  geom_point() + 
  geom_line() +
  ggtitle("Mean Y RMSE vs. Variance in Clusters") +
  xlab("Variance in Clusters") + 
  ylab("Mean Y RMSE") + 
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = 'bottom') + 
  scale_color_manual(name = "Effects",
                     labels=c('Fixed-Effects LASSO', 'Mixed-Effects LASSO'),
                      values = c("#56B4E9", "#CC79A7")) +
  facet_wrap(~snr_level,
             labeller = variable_labeller)

p
```


```{r}
tidy_plots_snr <- function(data, x, metric) {
  metric_colnames <- colnames(data %>% dplyr::select(contains(metric)))
  data_subset <- data %>%
    dplyr::select(c(contains(metric), x,
                    "mean_adj_r_squared", "mean_icc"))
  dataset_tidy <- data_subset %>%
    pivot_longer(cols = metric_colnames, 
                 names_to = c('.value', 'effects'),
                 names_pattern = paste0("^(\\w+_",
                                      metric,
                                      ")_(\\w+)"))
  
  dataset_to_plot <- dataset_tidy %>%
    mutate(!!paste0(metric, "_min") := get(paste0("mean_", metric)) -
             get(paste0("sd_", metric)),
           !!paste0(metric, "_max") := get(paste0("mean_", metric)) +
             get(paste0("sd_", metric)))

  
  p <- ggplot(data = dataset_to_plot, 
       mapping = aes(x = get(x), y = get(paste0("mean_", metric)),
                     ymin = get(paste0(metric, "_min")),
                     ymax = get(paste0(metric, "_max")),
                     group = factor(effects),
                     color = factor(effects))) + 
    geom_point() + 
    geom_line() +
    geom_ribbon(alpha = 0.25) +
    ggtitle(paste("Mean", outcome_label[metric], "vs. SNR")) +
    xlab("Signal to Noise Ratio") + 
    ylab(outcome_label[metric]) + 
    theme(plot.title = element_text(hjust = 0.5,
                                    size = 10),
        legend.position = 'bottom') + 
    scale_color_manual(name = "Effects",
                     labels=c('Fixed-Effects LASSO', 
                              'Mixed-Effects LASSO'),
                      values = c("#56B4E9", "#CC79A7")) 
  
  if (metric == "s_hat") {
    p <- p + geom_hline(yintercept = 81, linetype = "dashed")
  }
  
  p
  
  ggsave(paste0("/Users/thupham/Desktop/thesis/plots/final_plots/",
       metric, "_", x, "_cluster.png"))
  
  return()
                 
  
}


tidy_plots_snr(snr_collapse, "snr", "s_hat")
tidy_plots_snr(snr_collapse, "snr", "F1")
tidy_plots_snr(snr_collapse, "snr", "beta_rmse")
tidy_plots_snr(snr_collapse, "snr", "y_rmse")

tidy_plots_snr(snr_collapse_cluster, "snr", "s_hat")
tidy_plots_snr(snr_collapse_cluster, "snr", "F1")
tidy_plots_snr(snr_collapse_cluster, "snr", "beta_rmse")
tidy_plots_snr(snr_collapse_cluster, "snr", "y_rmse")

```


```{r}
# ggsave("/Users/thupham/Desktop/thesis/plots/F1_score.png", width = 9)
# try to make this into a function

outcome_label <- list("y_rmse" = "Y RMSE",
                      "beta_rmse" = "Beta RMSE",
                      "s_hat" = "Number of Estimated Non-Zero Coefficients",
                      "F1" = "F Score")

x_label <- list("sigma_r" = "Variance in Cluster",
                "scale" = "Number of True Non-Zero Coefficients")

tidy_plots <- function(data, x, metric) {
  metric_colnames <- colnames(data %>% dplyr::select(contains(metric)))
  data_subset <- data %>%
    dplyr::select(c(contains(metric),
                    "snr_level", x,
                    "mean_adj_r_squared", "mean_icc"))
  dataset_tidy <- data_subset %>%
    pivot_longer(cols = metric_colnames, 
                 names_to = c('.value', 'effects'),
                 names_pattern = paste0("^(\\w+_",
                                      metric,
                                      ")_(\\w+)"))
  
  dataset_to_plot <- dataset_tidy %>%
    mutate(!!paste0(metric, "_min") := get(paste0("mean_", metric)) -
             get(paste0("sd_", metric)),
           !!paste0(metric, "_max") := get(paste0("mean_", metric)) +
             get(paste0("sd_", metric)))

  
  p <- ggplot(data = dataset_to_plot, 
       mapping = aes(x = get(x), y = get(paste0("mean_", metric)),
                     ymin = get(paste0(metric, "_min")),
                     ymax = get(paste0(metric, "_max")),
                     group = factor(effects),
                     color = factor(effects))) + 
    geom_point() + 
    geom_line() +
    geom_ribbon(alpha = 0.25) +
    ggtitle(paste("Mean", outcome_label[metric], "vs.",
                x_label[x])) +
    xlab(x_label[x]) + 
    ylab(outcome_label[metric]) + 
    theme(plot.title = element_text(hjust = 0.5,
                                    size = 10),
        legend.position = 'bottom') + 
    scale_color_manual(name = "Effects",
                     labels=c('Fixed-Effects LASSO', 
                              'Mixed-Effects LASSO'),
                      values = c("#56B4E9", "#CC79A7")) +
    facet_wrap(~snr_level,
             labeller = variable_labeller)
  
  if (metric == "s_hat") {
    p <- p + geom_hline(yintercept = 81, linetype = "dashed")
  }
  
  p
  
  ggsave(paste0("/Users/thupham/Desktop/thesis/plots/final_plots/",
       metric, "_", x, ".png"))
  
  return()
                 
  
}

tidy_plots(sigma_r_snr, "sigma_r", "s_hat")
tidy_plots(sigma_r_snr, "sigma_r", "F1")
tidy_plots(sigma_r_snr, "sigma_r", "beta_rmse")
tidy_plots(sigma_r_snr, "sigma_r", "y_rmse")

tidy_plots(scale_snr, "scale", "s_hat")
tidy_plots(scale_snr, "scale", "F1")
tidy_plots(scale_snr, "scale", "beta_rmse")
tidy_plots(scale_snr, "scale", "y_rmse")

```

```{r}
# "tidy F1"
data_crashed_f1 <- collapsed_crash %>%
  select(snr, mean_F1_fixed, mean_F1_mixed) %>%
  pivot_longer(cols = c(mean_F1_fixed, mean_F1_mixed),
               values_to = "score",
               names_to = "effects")
# idea for NA values in certain metrics -- have a threshold?
# in data generating process, sort beta coefficients from largest to smallest in magnitude (so that you can more easily see whether LASSO keeps around the early coefficients, etc.

# anything above default is good
# anything below default / 2 is bad
# anything in between is indifferent
```

```{r}
p <- ggplot(data = data_crashed_f1, 
       mapping = aes(x = snr, y = F1,
                     group = factor(effects),
                     color = factor(effects))) + 
  geom_line() +
  ggtitle("Mean F1 Score vs. Signal-to-Noise Ratio") +
  xlab("Signal-to-Noise Ratio") + 
  ylab("Mean F1 Score") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  scale_color_manual(name = "Effects",
                     labels=c('Fixed-Effects LASSO', 'Mixed-Effects LASSO'),
                      values = c('blue', 'red'))

ggsave("/Users/thupham/Desktop/thesis/plots/F1_score.png", width = 9)
```


```{r}
data_crashed_rmse <- collapsed_crash %>%
  select(snr, mean_y_rmse_mixed, mean_y_rmse_fixed) %>%
  pivot_longer(cols = c(mean_y_rmse_mixed, mean_y_rmse_fixed), 
               values_to = "y_rmse",
               names_to = "effects")
```


```{r}
p <- ggplot(data = data_crashed_rmse, 
       mapping = aes(x = snr, y = y_rmse,
                     group = factor(effects),
                     color = factor(effects))) + 
  geom_line() +
  ggtitle("Mean Predicted RMSE vs. Signal-to-Noise Ratio") +
  xlab("Signal-to-Noise Ratio") + 
  ylab("Mean Y-Hat RMSE") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  scale_color_manual(name = "Effects",
                     labels=c('Fixed-Effects LASSO', 'Mixed-Effects LASSO'),
                      values = c('blue', 'red'))

p

ggsave("/Users/thupham/Desktop/thesis/plots/rmse.png")
```

```{r}
data_crashed_beta_rmse <- collapsed_crash_snr %>%
  select(snr, mean_beta_rmse_mixed, mean_beta_rmse_fixed) %>%
  pivot_longer(cols = c(mean_beta_rmse_mixed, mean_beta_rmse_fixed), 
               values_to = "beta_rmse",
               names_to = "effects")
```


```{r}
p <- ggplot(data = data_crashed_beta_rmse, 
       mapping = aes(x = snr, y = beta_rmse,
                     group = factor(effects),
                     color = factor(effects))) + 
  geom_line() +
  ggtitle("Mean Beta RMSE vs. Signal-to-Noise Ratio") +
  xlab("Signal-to-Noise Ratio") + 
  ylab("Mean Beta RMSE") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  scale_color_manual(name = "Effects",
                     labels=c('Fixed-Effects LASSO', 'Mixed-Effects LASSO'),
                      values = c('blue', 'red'))

p

ggsave("/Users/thupham/Desktop/thesis/plots/beta_rmse.png")
```



## new with data run (but this one also crashed)
```{r}
crashed_data_2 <- read.csv('/Users/thupham/Desktop/thesis/concat_results/with_data_run.csv')
```


```{r}
collapsed_crash_snr_2 <- crashed_data_2 %>% 
  group_by(snr) %>%
  summarize(across(mean_adj_r_squared:last_col(), ~ mean(.x, na.rm = TRUE))) %>%
  ungroup()

collapsed_crash_s_2 <- crashed_data_2 %>%
  group_by(s) %>%
  summarize(across(mean_adj_r_squared:last_col(), ~ mean(.x, na.rm = TRUE))) %>%
  mutate(s_prop = s / 60) %>%
  ungroup()
```


```{r}
# faceted plot -- agreement vs snr. faceted by number of non-zero predictors
p <- ggplot(data = collapsed_crash_snr_2, 
       mapping = aes(x = snr, y = mean_agreement)) + 
  geom_line(color = "cadetblue3") + 
  geom_point(color = "cadetblue3") +
  geom_point(data = agreement, 
             mapping = aes(x = snr, y = mean_agreement)) + 
  geom_text(data = agreement, 
            mapping = aes(x = snr,
                   y = mean_agreement, 
                   label = "ELS@H Data"),
            nudge_x = 0.5, nudge_y = 0.025) + 
  ggtitle("Mean Agreement vs. Signal-to-Noise Ratio") +
  ylab("Mean Agreement") + 
  xlab("Signal-to-Noise Ratio") + 
  theme(plot.title = element_text(hjust = 0.5))

p
ggsave("/Users/thupham/Desktop/thesis/plots/agreement_snr_2.png")

## need to look at the actual value of agreement (e.g., if it's around 55%) -- does that mean both models are dealing with randomness in different ways, and which 
```


```{r}
# faceted plot -- agreement vs snr. faceted by number of non-zero predictors
p <- ggplot(data = collapsed_crash_s_2, 
       mapping = aes(x = s_prop, y = mean_agreement)) + 
  geom_line(color = "cadetblue3") + 
  geom_point(color = "cadetblue3") +
  geom_point(data = agreement, 
             mapping = aes(x = s, y = mean_agreement)) + 
  geom_text(data = agreement, 
            mapping = aes(x = s,
                   y = mean_agreement, 
                   label = "ELS@H Data"),
            nudge_x = 0.01, nudge_y = 0.025) + 
  ggtitle("Mean Agreement vs. Proportion of Non-Zero Coefficients") +
  xlab("Proportion of Non-Zero Coefficients") + 
  ylab("Mean Agreement") + 
  theme(plot.title = element_text(hjust = 0.5))

p
ggsave("/Users/thupham/Desktop/thesis/plots/agreement_s_2.png")
```


```{r}
# "tidy F1"
data_crashed_f1_2 <- collapsed_crash_snr_2 %>%
  dplyr::select(snr, mean_F1_fixed, mean_F1_mixed) %>%
  pivot_longer(cols = c(mean_F1_fixed, mean_F1_mixed), values_to = "F1",
               names_to = "effects")

```

```{r}
p <- ggplot(data = data_crashed_f1_2, 
       mapping = aes(x = snr, y = F1,
                     group = factor(effects),
                     color = factor(effects))) + 
  geom_line() +
  ggtitle("Mean F1 Score vs. Signal-to-Noise Ratio") +
  xlab("Signal-to-Noise Ratio") + 
  ylab("Mean F1 Score") + 
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = 'bottom') + 
  scale_color_manual(name = "Effects",
                     labels=c('Fixed-Effects LASSO', 'Mixed-Effects LASSO'),
                      values = c('olivedrab4', '#f032e6'))

p

ggsave("/Users/thupham/Desktop/thesis/plots/F1_score_2.png", width = 5)
```
```{r}
rmse <- data.frame(y_rmse = c(10.8713, 10.535),
                   effects = factor(c("mixed", "fixed")),
                   snr = rep(0.46, 2))
```


```{r}
data_crashed_rmse_2 <- collapsed_crash_snr_2 %>%
  dplyr::select(snr, mean_y_rmse_mixed, mean_y_rmse_fixed) %>%
  pivot_longer(cols = c(mean_y_rmse_mixed, mean_y_rmse_fixed), 
               values_to = "y_rmse",
               names_to = "effects")
```


```{r}
width_scale <- 8
# ratio <- with(data_crashed_rmse_2, diff(range(snr))/diff(range(y_rmse)))
p <- ggplot(data = data_crashed_rmse_2, 
       mapping = aes(x = snr, y = y_rmse,
                     group = factor(effects),
                     color = factor(effects))) + 
  geom_line() +
  geom_point(data = rmse, 
            mapping = aes(x = snr, y = y_rmse,
                          group = factor(effects), 
                          color = factor(effects)),
            size = 3, 
            alpha = 0.7) + 
  ggtitle("Mean Predicted RMSE vs. Signal-to-Noise Ratio") +
  xlab("Signal-to-Noise Ratio") + 
  ylab("Mean Y-Hat RMSE") +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = 'bottom',
        legend.text = element_text(size = 8)) +
  guides(color = guide_legend(nrow=2,byrow=TRUE)) +
  scale_color_manual(name = "",
                     labels=c('Mixed-Effects LASSO on ELS@H', 
                              'Fixed-Effects LASSO on Simulation',
                              'Mixed-Effects LASSO on Simulation',
                              'Fixed-Effects LASSO on ELS@H'),
                     values = c('red3', 'olivedrab4',
                                '#f032e6', 'deepskyblue2')) 
  # coord_fixed(ratio=ratio)
 
p

ggsave("/Users/thupham/Desktop/thesis/plots/rmse_2.png", width = 5)
```

```{r}
data_crashed_beta_rmse_2 <- collapsed_crash_snr_2 %>%
  dplyr::select(snr, mean_beta_rmse_mixed, mean_beta_rmse_fixed) %>%
  pivot_longer(cols = c(mean_beta_rmse_mixed, mean_beta_rmse_fixed), 
               values_to = "beta_rmse",
               names_to = "effects")
```


```{r}
p <- ggplot(data = data_crashed_beta_rmse_2, 
       mapping = aes(x = snr, y = beta_rmse,
                     group = factor(effects),
                     color = factor(effects))) + 
  geom_line() +
  ggtitle("Mean Beta RMSE vs. Signal-to-Noise Ratio") +
  xlab("Signal-to-Noise Ratio") + 
  ylab("Mean Beta RMSE") + 
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = 'bottom') + 
  scale_color_manual(name = "Effects",
                     labels=c('Fixed-Effects LASSO', 'Mixed-Effects LASSO'),
                      values = c('olivedrab4', '#f032e6'))

p

ggsave("/Users/thupham/Desktop/thesis/plots/beta_rmse_2.png", width = 5)
```


## discarded plots

```{r}
# faceted plot -- agreement vs snr. faceted by number of non-zero predictors
p <- ggplot(data = collapsed_crash_snr, 
       mapping = aes(x = snr, y = mean_agreement)) + 
  geom_line(color = "cadetblue3") + 
  geom_point(color = "cadetblue3") +
  geom_point(data = agreement, 
             mapping = aes(x = snr, y = mean_agreement)) + 
  geom_text(data = agreement, 
            mapping = aes(x = snr,
                   y = mean_agreement, 
                   label = "ELS@H Data"),
            nudge_x = 0.5, nudge_y = 0.025) + 
  ggtitle("Mean Agreement vs. Signal-to-Noise Ratio") +
  ylab("Mean Agreement") + 
  xlab("Signal-to-Noise Ratio") + 
  theme(plot.title = element_text(hjust = 0.5))

p
ggsave("/Users/thupham/Desktop/thesis/plots/agreement_snr.png")

## need to look at the actual value of agreement (e.g., if it's around 55%) -- does that mean both models are dealing with randomness in different ways, and which 

# TODO: ditch type 2 because pairwise covariance
```


```{r}
# faceted plot -- agreement vs snr. faceted by number of non-zero predictors
p <- ggplot(data = collapsed_crash_s, 
       mapping = aes(x = s_prop, y = mean_agreement)) + 
  geom_line(color = "cadetblue3") + 
  geom_point(color = "cadetblue3") +
  geom_point(data = agreement, 
             mapping = aes(x = s, y = mean_agreement)) + 
  geom_text(data = agreement, 
            mapping = aes(x = s,
                   y = mean_agreement, 
                   label = "ELS@H Data"),
            nudge_x = 0.01, nudge_y = 0.025) + 
  ggtitle("Mean Agreement vs. Proportion of Non-Zero Coefficients") +
  xlab("Proportion of Non-Zero Coefficients") + 
  ylab("Mean Agreement") + 
  theme(plot.title = element_text(hjust = 0.5))

p
ggsave("/Users/thupham/Desktop/thesis/plots/agreement_s.png")
```
